### ISSUE TITLE
Does'nt work addDates()

### ISSUE THREAD

**Issue by FujiHaruka** [the-labo/the-date#2]
https://github.com/the-labo/the-date/blob/master/lib/mixins/addMix.js#L76

`addDays()` は動きますが、`addDates()` は動きません。

momentのadd()には`.add(1, 'dates')` がないので。 https://momentjs.com/docs/#/manipulating/add/

**Comment by okunishinishi** [comment]
https://momentjs.com/docs/#/manipulating/add/

**Comment by okunishinishi** [comment]
done
